SYMBOL_MAP = {
    "Bullseye": "10",
    "one": "11",
    "two": "12",
    "three": "13",
    "four": "14",
    "five": "15",
    "six": "16",
    "seven": "17",
    "eight": "18",
    "nine": "19",
    "Alphabet_A": "20",
    "Alphabet_B": "21",
    "Alphabet_C": "22",
    "Alphabet_D": "23",
    "Alphabet_E": "24",
    "Alphabet_F": "25",
    "Alphabet_G": "26",
    "Alphabet_H": "27",
    "Alphabet_S": "28",
    "Alphabet_T": "29",
    "Alphabet_U": "30",
    "Alphabet_v": "31",
    "Alphabet_w": "32",
    "Alphabet_x": "33",
    "Alphabet_y": "34",
    "Alphabet_z": "35",
    "up_arrow": "36",
    "down_arrow": "37",
    "right_arrow": "38",
    "left_arrow": "39",
    "Stop": "40"
}
# SYMBOL_MAP = {
#     "10": "Bullseye",
#     "11": "One",
#     "12": "Two",
#     "13": "Three",
#     "14": "Four",
#     "15": "Five",
#     "16": "Six",
#     "17": "Seven",
#     "18": "Eight",
#     "19": "Nine",
#     "20": "A",
#     "21": "B",
#     "22": "C",
#     "23": "D",
#     "24": "E",
#     "25": "F",
#     "26": "G",
#     "27": "H",
#     "28": "S",
#     "29": "T",
#     "30": "U",
#     "31": "V",
#     "32": "W",
#     "33": "X",
#     "34": "Y",
#     "35": "Z",
#     "36": "up_arrow",
#     "37": "down_arrow",
#     "38": "right_arrow",
#     "39": "left_arrow",
#     "40": "Stop"
# }
